//! QShield recovery phrase v1 vectors (`tests/vectors/recovery/recovery-v1.json`).
//! Regenerate with `QSHIELD_REGENERATE=1 cargo test -p qshield-client --test recovery_vectors`.

use qshield_client::recovery::{phrase_from_seed, seed_from_phrase};
use qshield_client::{LocalKey, PqSigner};
use serde_json::json;
use sha2::{Digest, Sha256};

const PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../tests/vectors/recovery/recovery-v1.json"
);

#[test]
fn recovery_vectors() {
    let mut v = vec![];
    for tag in ["zero", "ones", "a", "b", "c"] {
        let seed: [u8; 32] = match tag {
            "zero" => [0; 32],
            "ones" => [0xff; 32],
            t => Sha256::digest(format!("recovery vector {t}")).into(),
        };
        let phrase = phrase_from_seed(&seed);
        assert_eq!(*seed_from_phrase(&phrase).unwrap(), seed);
        v.push(json!({
            "seed_hex": hex::encode(seed),
            "phrase": phrase.as_str(),
            "key_id_hex": hex::encode(LocalKey::from_seed(&seed).key_id()),
        }));
    }
    let doc = json!({
        "description": "QShield recovery phrase v1: 24 BIP-39 English words = seed (256 bits) || SHA-256(\"QSHIELD_RECOVERY_PHRASE_V1\" || 0x01 || seed)[0]. Generated by crates/qshield-client/tests/recovery_vectors.rs.",
        "wordlist_sha256": "2f5eed53a4727b4bf8880d8f3f199efc90e58503646d9ff8eff3a2ed3b24dbda",
        "vectors": v,
        "invalid": [
            "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art",
            "abandon abandon",
        ],
    });
    let text = serde_json::to_string_pretty(&doc).unwrap() + "\n";
    if std::env::var("QSHIELD_REGENERATE").is_ok() {
        std::fs::write(PATH, &text).unwrap();
    }
    assert_eq!(std::fs::read_to_string(PATH).expect("vector file"), text);
}
